# Generated by Django 3.0.3 on 2020-03-09 01:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='nowosci',
            name='nazwaZdj',
            field=models.FileField(blank=True, null=True, upload_to=''),
        ),
    ]
