# Generated by Django 3.0.3 on 2020-03-09 01:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_auto_20200309_0233'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='nowosci',
            name='CzyMaPodStrone',
        ),
        migrations.RemoveField(
            model_name='nowosci',
            name='link',
        ),
    ]
